version: '3.9'

services:
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx.Dockerfile
        volumes:
        -   ./:/var/www
        -   ./docker/nginx/ssl:/etc/nginx/ssl
        ports:
        -   8000:443
        volumes_from:
            -   php-fpm
        links:
            -   php-fpm

    php-fpm:
        build:
            context: .
            dockerfile: docker/php-fpm.Dockerfile
        volumes:
        -   ./:/var/www
        depends_on:
            -   mysql
            -   redis
            -   elasticserach
        environment:
            -   DB_PORT=3306
            -   DB_HOST=mysql
            -   REDIS_PORT=6379
            -   REDIS_HOST=redis
            -   ELASTICSEARCH_HOST=elasticsearch:9200

    mysql:
        image: mysql:5.7.16
        volumes:
        -   ./storage/docker/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: agency
        ports:
        -   33063:3306

    # mysql-test:
    #     image: mysql:5.7.16
    #     volumes:
    #         -   ./storage/docker/mysql-test:/var/lib/mysql
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_DATABASE: agency_test
    #     ports:
    #         -   33062:3306

    node:
        build:
            context: .
            dockerfile: docker/node.Dockerfile
        volumes:
            -   ./:/var/www
        tty: true

    redis:
        image: redis:3.0
        ports:
        -   63791:6379

    elasticserach:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
        environment:
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        mem_limit: 1073741824
        volumes:
        -   ./storage/docker/elasticsearch:/usr/share/elasticsearch/data
        ports:
        -   9201:9200



